package org.wquery.engine
import org.wquery.WQueryEvaluationException
import org.wquery.model.{WordNet, IntegerType, Relation, DataType, StringType, SenseType, SynsetType, Sense, BasicType, UnionType, ValueType, TupleType, AggregateFunction, ScalarFunction, FloatType, FunctionArgumentType, Arc, DataSet, DataSetBuffer, DataSetBuffers}
import scala.collection.mutable.ListBuffer

sealed abstract class Expr

sealed abstract class EvaluableExpr extends Expr {
  def evaluate(functions: FunctionSet, wordNet: WordNet, bindings: Bindings, context: Context): DataSet
}

sealed abstract class ContextFreeExpr extends EvaluableExpr {
  def evaluate(functions: FunctionSet, wordNet: WordNet, bindings: Bindings): DataSet

  def evaluate(functions: FunctionSet, wordNet: WordNet, bindings: Bindings, context: Context): DataSet = evaluate(functions, wordNet, bindings)
}

sealed abstract class BindingsFreeExpr extends ContextFreeExpr {
  def evaluate(functions: FunctionSet, wordNet: WordNet): DataSet

  def evaluate(functions: FunctionSet, wordNet: WordNet, bindings: Bindings): DataSet = evaluate(functions, wordNet)
}

sealed abstract class FunctionsFreeExpr extends BindingsFreeExpr {
  def evaluate(wordNet: WordNet): DataSet

  def evaluate(functions: FunctionSet, wordNet: WordNet): DataSet = evaluate(wordNet)
}

sealed abstract class SelfEvaluableExpr extends FunctionsFreeExpr {
  def evaluate(): DataSet

  def evaluate(wordNet: WordNet): DataSet = evaluate
}

/*
 * Imperative expressions
 */

sealed abstract class ImperativeExpr extends EvaluableExpr

case class EmissionExpr(expr: EvaluableExpr) extends ImperativeExpr {
  def evaluate(functions: FunctionSet, wordNet: WordNet, bindings: Bindings, context: Context) = {
    expr.evaluate(functions, wordNet, bindings, context)
  }
}

case class IteratorExpr(vars: List[String], mexpr: EvaluableExpr, iexpr: ImperativeExpr) extends ImperativeExpr {
  def evaluate(functions: FunctionSet, wordNet: WordNet, bindings: Bindings, context: Context) = {
    val mresult = mexpr.evaluate(functions, wordNet, bindings, context)
    val tupleBindings = new Bindings(Some(bindings))
    val buffer = new DataSetBuffer

    for (tuple <- mresult.paths) {
      if (tuple.size >= vars.size) {  
        for (i <- 0 until vars.size) {
          tupleBindings.bind(vars(i), tuple(i))
        }
    
        buffer.append(iexpr.evaluate(functions, wordNet, tupleBindings, context))
      } else {
        throw new WQueryEvaluationException("A tuple generated by a path expression in an iterator contains" +
          " an insufficient number of elements to bind all variables")      
      }
    }

    buffer.toDataSet
  }
}

case class IfElseExpr(cexpr: EvaluableExpr, iexpr: ImperativeExpr, eexpr: Option[ImperativeExpr]) extends ImperativeExpr {
  def evaluate(functions: FunctionSet, wordNet: WordNet, bindings: Bindings, context: Context) = {
    val cresult = cexpr.evaluate(functions, wordNet, bindings, context)

    if (cresult.isTrue) {
      iexpr.evaluate(functions, wordNet, bindings, context)
    } else {
      eexpr match {
        case Some(eexpr) =>
          eexpr.evaluate(functions, wordNet, bindings, context)
        case None =>
          DataSet.empty
      }
    }
  }
}

case class BlockExpr(exprs: List[ImperativeExpr]) extends ImperativeExpr {
  def evaluate(functions: FunctionSet, wordNet: WordNet, bindings: Bindings, context: Context) = {
    val blockBindings = new Bindings(Some(bindings))
    val buffer = new DataSetBuffer

    for (expr <- exprs) {
      buffer.append(expr.evaluate(functions, wordNet, blockBindings, context))
    }

    buffer.toDataSet
  }
}

case class EvaluableAssignmentExpr(vars: List[String], expr: EvaluableExpr) extends ImperativeExpr {
  def evaluate(functions: FunctionSet, wordNet: WordNet, bindings: Bindings, context: Context) = {
    val eresult = expr.evaluate(functions, wordNet, bindings, context)

    if (eresult.paths.size == 1) {
      val tuple = eresult.paths.head

      if (vars.size == tuple.size) {
        for (i <- 0 until vars.size) {
          bindings.bind(vars(i), tuple(i))
        }

        DataSet.empty
      } else {
        throw new WQueryEvaluationException("A tuple generated by a path expression in an assignment contains" +
          " an insufficient number of elements to bind all variables")
      }

      DataSet.empty
    } else {
      throw new WQueryEvaluationException("A multipath expression in an assignment should contain exactly one tuple")
    }
  }
}

case class RelationalAssignmentExpr(name: String, rexpr: RelationalExpr) extends ImperativeExpr {
  def evaluate(functions: FunctionSet, wordNet: WordNet, bindings: Bindings, context: Context) = {
    bindings.bind(name, rexpr)
    DataSet.empty
  }
}

/*
 * Multipath expressions
 */
case class BinaryPathExpr(op: String, left: EvaluableExpr, right: EvaluableExpr) extends EvaluableExpr {
  def evaluate(functions: FunctionSet, wordNet: WordNet, bindings: Bindings, context: Context) = {
    val leval = left.evaluate(functions, wordNet, bindings, context)
    val reval = right.evaluate(functions, wordNet, bindings, context)

    op match {
      case "," =>
        join(leval, reval)
      case op =>
        DataSet(
          op match {
            case "union" =>
              leval.paths union reval.paths
            case "except" =>
              leval.paths.filterNot(reval.paths.contains)
            case "intersect" =>
              leval.paths intersect reval.paths
            case _ =>
              throw new IllegalArgumentException("Unknown binary path operator '" + op + "'")
          })
    }
  }

  def join(left: DataSet, right: DataSet) = {
    val leftPathVarNames = left.pathVars.keys.toSeq
    val leftStepVarNames = left.stepVars.keys.toSeq
    val rightPathVarNames = right.pathVars.keys.toSeq
    val rightStepVarNames = right.stepVars.keys.toSeq
    val pathBuffer = DataSetBuffers.createPathBuffer
    val pathVarBuffers = DataSetBuffers.createPathVarBuffers(leftPathVarNames ++ rightPathVarNames)
    val stepVarBuffers = DataSetBuffers.createStepVarBuffers(leftStepVarNames ++ rightStepVarNames)
    
    for (i <- 0 until left.pathCount) {
      for (j <- 0 until right.pathCount ) {
        val leftTuple = left.paths(i)
        val rightTuple = right.paths(j)        
          
        pathBuffer.append(leftTuple ++ rightTuple)
        leftPathVarNames.foreach(x => pathVarBuffers(x).append(left.pathVars(x)(i)))
        leftStepVarNames.foreach(x => stepVarBuffers(x).append(left.stepVars(x)(i)))
        
        val offset = leftTuple.size
        
        rightPathVarNames.foreach { x => 
          val pos = right.pathVars(x)(j)          
          pathVarBuffers(x).append((pos._1 + offset, pos._2 + offset))
        }
        
        rightStepVarNames.foreach(x => stepVarBuffers(x).append(right.stepVars(x)(j) + offset))
      }
    }

    DataSet.fromBuffers(pathBuffer, pathVarBuffers, stepVarBuffers)
  }
}

/*
 * Arithmetic expressions
 */
case class BinaryArithmExpr(op: String, left: EvaluableExpr, right: EvaluableExpr) extends EvaluableExpr {
  def evaluate(functions: FunctionSet, wordNet: WordNet, bindings: Bindings, context: Context) = {
    val lresult = left.evaluate(functions, wordNet, bindings, context)
    val rresult = right.evaluate(functions, wordNet, bindings, context)

    if (lresult.minPathSize > 0 && rresult.minPathSize > 0 && lresult.isNumeric(0) && rresult.isNumeric(0)) {
      if (lresult.getType(0) == IntegerType && rresult.getType(0) == IntegerType) {
        combineUsingIntArithmOp(op, lresult.paths.map( x => x.last.asInstanceOf[Int]), rresult.paths.map( x => x.last.asInstanceOf[Int]))
      } else {
        combineUsingDoubleArithmOp(op, 
          lresult.paths.map(x => x.last).map {
            case x: Double => x            
            case x: Int => x.doubleValue
          },
          rresult.paths.map(x => x.last).map {
            case x: Double => x              
            case x: Int => x.doubleValue
          }
        )
      }
    } else {
      throw new WQueryEvaluationException("Operator '" + op + "' requires numeric type ended datapaths") 
    }
  }

  def combineUsingIntArithmOp(op: String, leval: List[Int], reval: List[Int]) = {
    val func: (Int, Int) => Int = op match {
      case "+" =>
        (x, y) => x + y
      case "-" =>
        (x, y) => x - y
      case "*" =>
        (x, y) => x * y
      case "/" =>
        (x, y) => x / y
      case "%" =>
        (x, y) => x % y
      case _ =>
        throw new IllegalArgumentException("Unknown binary arithmetic operator '" + op + "'")
    }
    
    combine[Int](func, leval, reval)
  }    
  
  def combineUsingDoubleArithmOp(op: String, leval: List[Double], reval: List[Double]) = {
    val func: (Double, Double) => Double = op match {
      case "+" =>
        (x, y) => x + y
      case "-" =>
        (x, y) => x - y
      case "*" =>
        (x, y) => x * y
      case "/" =>
        (x, y) => x / y
      case "%" =>
        (x, y) => x % y
      case _ =>
        throw new IllegalArgumentException("Unknown binary arithmetic operator '" + op + "'")
    }
    
    combine[Double](func, leval, reval)
  }  

  def combine[A](func: (A, A) => A, leval: List[A], reval: List[A]) = {
    val buffer = new ListBuffer[List[Any]]

    for (lval <- leval) {
      for (rval <- reval) {
        buffer append List(func(lval, rval))
      }
    }

    DataSet(buffer.toList)
  }

}

case class MinusExpr(expr: EvaluableExpr) extends EvaluableExpr {
  def evaluate(functions: FunctionSet, wordNet: WordNet, bindings: Bindings, context: Context) = {
    val eresult = expr.evaluate(functions, wordNet, bindings, context)

    if (eresult.isNumeric(0)) {
        DataSet(eresult.paths.map(x => x.last).map {
            case x: Int => List(-x)
            case x: Double => List(-x)
        })
    } else {
      throw new WQueryEvaluationException("Unary '-' requires a context that consist of integer or float singletons")       
    }
  }
}

/* 
 * Function call expressions
 */
case class FunctionExpr(name: String, args: EvaluableExpr) extends EvaluableExpr {
  def evaluate(functions: FunctionSet, wordNet: WordNet, bindings: Bindings, context: Context) = {
    val avalues = args.evaluate(functions, wordNet, bindings, context)
    
    val atypes: List[FunctionArgumentType] = if (avalues.minPathSize  != avalues.maxPathSize ) {
      List(TupleType)
    } else {
      ((avalues.maxPathSize - 1) to 0 by -1).map(x => avalues.getType(x)).toList.map {
          case UnionType(utypes) =>
            if (utypes == Set(FloatType, IntegerType)) ValueType(FloatType) else TupleType
          case t: BasicType =>
            ValueType(t)
      }
    }

    functions.getFunction(name, atypes) match {
      case Some(func) =>
        invokeFunction(func, atypes, avalues)
      case None =>
        // promote arg types from integers to floats
        functions.getFunction(
          name,
          atypes.map {
            case ValueType(IntegerType) => ValueType(FloatType)
            case t => t
          }) match {
          case Some(func) => 
            invokeFunction(func, atypes, avalues)
          case None =>
            invokeFunction(functions.demandFunction(name, List(TupleType)), atypes, avalues)
        }
    }
  }
  
  private def invokeFunction(fdesc: (org.wquery.model.Function, java.lang.reflect.Method), atypes: List[FunctionArgumentType], avalues: DataSet) = {
    fdesc match {
      case (func: AggregateFunction, method) =>
        method.invoke(WQueryFunctions, avalues).asInstanceOf[DataSet]
      case (func: ScalarFunction, method) =>
        val buffer = new ListBuffer[List[Any]]()
        val margs = new Array[AnyRef](atypes.size)
        var stop = false

        for (tuple <- avalues.paths) {
          for (i <- 0 until margs.size)
            margs(i) = tuple(i).asInstanceOf[AnyRef]

          buffer.append(List(method.invoke(WQueryFunctions, margs: _*)))
        }

        func.result match {
          case ValueType(dtype) =>
            DataSet(buffer.toList)
          case TupleType =>
            throw new RuntimeException("ScalarFunction '" + func.name + "' returned TupleType")
        }
    }      
  }
}

/*
 * Path related expressions
 */
case class StepExpr(lexpr: EvaluableExpr, rexpr: TransformationDesc) extends EvaluableExpr with VariableBindings {
  def evaluate(functions: FunctionSet, wordNet: WordNet, bindings: Bindings, context: Context) = {
    rexpr match {
      case RelationTransformationDesc(pos, rexpr, decls) =>
        val lresult = lexpr.evaluate(functions, wordNet, bindings, context)

        bind(rexpr.transform(wordNet, bindings, context, lresult, pos, false), decls)
      case FilterTransformationDesc(cond, decls) =>
        val lresult = lexpr.evaluate(functions, wordNet, bindings, context)

        bind(DataSet(lresult.paths.filter { tuple => 
          cond.satisfied(functions, wordNet, bindings, Context(tuple))
        }), decls)
    }
  }
}

trait VariableBindings {
  def bind(dataSet: DataSet, decls: List[VariableLit]) = {
    if (decls != Nil) {          
      val pathVarBuffers = DataSetBuffers.createPathVarBuffers(decls.filter(x => (x.isInstanceOf[PathVariableLit] && x.value != "_")).map(_.value))                
      val stepVarBuffers = DataSetBuffers.createStepVarBuffers(decls.filterNot(x => (x.isInstanceOf[PathVariableLit] || x.value == "_")).map(_.value))        
    
      getPathVariablePosition(decls) match {
        case Some(pathVarPos) => 
          val leftVars = decls.slice(0, pathVarPos).map(_.value).zipWithIndex.filterNot{_._1 == "_"}.toMap
          val rightVars = decls.slice(pathVarPos + 1, decls.size).map(_.value).reverse.zipWithIndex.filterNot{_._1 == "_"}.toMap   
          val pathVarStart = leftVars.size
          val pathVarEnd = rightVars.size
          val pathVarBuffer = pathVarBuffers(decls(pathVarPos).value)
      
          for (tuple <- dataSet.paths) {  
            dataSet.paths.foreach(tuple => bindVariablesFromRight(rightVars, stepVarBuffers, tuple.size))            
            pathVarBuffer.append((pathVarStart, tuple.size - 1 - pathVarEnd))
            dataSet.paths.foreach(tuple => bindVariablesFromLeft(leftVars, stepVarBuffers))            
          }
        case None =>
          val rightVars = decls.map(_.value).reverse.zipWithIndex.filterNot{_._1 == "_"}.toMap        
        
          dataSet.paths.foreach(tuple => bindVariablesFromRight(rightVars, stepVarBuffers, tuple.size))      
      }
    
      DataSet(dataSet.paths, dataSet.pathVars ++ pathVarBuffers.mapValues(_.toList), dataSet.stepVars ++ stepVarBuffers.mapValues(_.toList))
    } else {
      dataSet
    }
  }
  
  private def getPathVariablePosition(decls: List[VariableLit]) = {
    val pathVarPos = decls.indexWhere{_.isInstanceOf[PathVariableLit]}
    
    if (pathVarPos != decls.lastIndexWhere{_.isInstanceOf[PathVariableLit]}) {
      throw new WQueryEvaluationException("Variable list '" + decls.map { 
        case PathVariableLit(v) => "@" + v 
        case StepVariableLit(v) => "$" + v
      }.mkString + "' contains more than one path variable")
    } else {
      if (pathVarPos != -1)
        Some(pathVarPos)
      else
        None
    }
  }
  
  private def bindVariablesFromLeft(vars: Map[String, Int], varIndexes: Map[String, ListBuffer[Int]]) {
    for ((v, pos) <- vars)
      varIndexes(v).append(pos)
  }    
  
  private def bindVariablesFromRight(vars: Map[String, Int], varIndexes: Map[String, ListBuffer[Int]], tupleSize: Int) {
    for ((v, pos) <- vars) {
      val index = tupleSize - 1 - pos
      
      if (index >= 0)
        varIndexes(v).append(index)
      else 
        throw new WQueryEvaluationException("Variable $" + v + " cannot be bound")
    }
  }
}

sealed abstract class TransformationDesc extends Expr

case class RelationTransformationDesc(pos: Int, expr: RelationalExpr, decls: List[VariableLit]) extends TransformationDesc
case class FilterTransformationDesc(expr: ConditionalExpr, decls: List[VariableLit]) extends TransformationDesc

case class PathExpr(expr: EvaluableExpr) extends EvaluableExpr {
  def evaluate(functions: FunctionSet, wordNet: WordNet, bindings: Bindings, context: Context) = { //TODO extend this method or remove this class
    expr.evaluate(functions, wordNet, bindings, context)
  }
}

/*
 * Relational Expressions
 */
sealed abstract class RelationalExpr extends Expr {
  def transform(wordNet: WordNet, bindings: Bindings, context: Context, data: DataSet, pos: Int, force: Boolean): DataSet
}

case class UnaryRelationalExpr(idLits: List[IdentifierLit]) extends RelationalExpr {
  def transform(wordNet: WordNet, bindings: Bindings, context: Context, data: DataSet, pos: Int, force: Boolean) = { //TODO this method is ugly
    if (force || idLits.size > 1) {
      if (pos == 0) {
        if (context.isEmpty) {
          useIdentifiersAsGenerator(idLits.map(x => x.value), wordNet).getOrElse(
            throw new WQueryEvaluationException("Relation '" + idLits.head.value + "' not found")            
          )
        } else {
          useIdentifiersAsTransformation(idLits.map(x => x.value), wordNet, data, 1)
        }
      } else {
        useIdentifiersAsTransformation(idLits.map(x => x.value), wordNet, data, pos)  
      }
    } else {
      idLits.head match {
        case QuotedIdentifierLit(wordForm) =>
          if (pos == 0) {
            useIdentifierAsGenerator(wordForm, wordNet, context)
          } else {
            throw new WQueryEvaluationException("Quoted identifier found after '.'")
          }
        case NotQuotedIdentifierLit(id) =>
          if (pos == 0) { // we are in a generator 
            if (context.isEmpty) { // we are not in a filter
              useIdentifiersAsGenerator(List(id), wordNet)
                .getOrElse(useIdentifierAsGenerator(id, wordNet, context))
            } else {
              useIdentifierAsRelationalExprAlias(id, wordNet, bindings, context, data, pos, force) 
                .getOrElse(
                  if (wordNet.containsRelation(id, data.getType(0), Relation.Source)) {
                    useIdentifiersAsTransformation(List(id), wordNet, data, 1)
                  } else {
                    useIdentifierAsGenerator(id, wordNet, context)
                  }                    
                )
            }
          } else {
            useIdentifierAsRelationalExprAlias(id, wordNet, bindings, context, data, pos, force)
              .getOrElse(useIdentifiersAsTransformation(List(id), wordNet, data, pos))           
          }
      }
    }
  }
  
  private def useIdentifiersAsGenerator(ids: List[String], wordNet: WordNet) = {
    ids match {
      case first::second::dests =>
        wordNet.findRelationsByNameAndSource(second, first) match {
          case head::_ =>
            Some(DataSet(wordNet.getPaths(head, first, dests)))  
          case Nil =>
            wordNet.findRelationsByNameAndSource(first, Relation.Source) match {
              case head::_ =>
                Some(DataSet(wordNet.getPaths(head, Relation.Source, second::dests)))  
              case Nil =>
                None
            }          
        }          
      case List(head) =>
        wordNet.findRelationsByNameAndSource(ids.head, Relation.Source) match {
          case head::_ =>
            Some(DataSet(wordNet.getPaths(head, Relation.Source, head.argumentNames.filter(_ != Relation.Source))))          
          case Nil =>
            None        
        }        
      case Nil =>
          None        
    }
  }

  private def useIdentifierAsGenerator(id: String, wordNet: WordNet, context: Context) = {
    id match {
      case "" =>
        DataSet.fromList(wordNet.words.toList)
      case "false" =>
        DataSet.fromValue(false)
      case "true" =>
        DataSet.fromValue(true)
      case id =>
        DataSet.fromOptionalValue(wordNet.getWordForm(id))                    
    }
  }

  private def useIdentifiersAsTransformation(ids: List[String], wordNet: WordNet, data: DataSet, pos: Int) = {
    val sourceType = data.getType(pos - 1)  
    val (relation, source, dests) = ids match {
      case List(relationName) =>
        (wordNet.demandRelation(relationName, sourceType, Relation.Source), Relation.Source, List(Relation.Destination))
      case List(left, right) =>
        wordNet.getRelation(left, sourceType, Relation.Source) match {
          case Some(relation) => 
            (relation, Relation.Source, List(right))
          case None =>
            (wordNet.demandRelation(right, sourceType, left), left, List(Relation.Destination))  
        }
      case first::second::dests =>
        wordNet.getRelation(first, sourceType, Relation.Source) match {
          case Some(relation) => 
            (relation, Relation.Source, second::dests)
          case None =>
            (wordNet.demandRelation(second, sourceType, first), first, dests)  
        }      
    }
    
    wordNet.follow(data, pos, relation, source, dests)            
  }
  
  private def useIdentifierAsRelationalExprAlias(id: String, wordNet: WordNet, bindings: Bindings, context: Context,
    data: DataSet, pos: Int, force: Boolean) = {
    bindings.lookup(id) match {
      case Some(rexpr: RelationalExpr) =>
        Some(rexpr.transform(wordNet, bindings, context, data, pos, force))
      case _ =>
        None
    }
  }
  
}

case class QuantifiedRelationalExpr(expr: RelationalExpr, quantifier: QuantifierLit) extends RelationalExpr {
  def transform(wordNet: WordNet, bindings: Bindings, context: Context, data: DataSet, pos: Int, force: Boolean) = {
    quantifier match {
      case QuantifierLit(1, Some(1)) =>
        expr.transform(wordNet, bindings, context, data, pos, force)
      case QuantifierLit(1, None) =>
        val pathVarNames = data.pathVars.keys.toSeq
        val stepVarNames = data.stepVars.keys.toSeq
        val pathBuffer = DataSetBuffers.createPathBuffer
        val pathVarBuffers = DataSetBuffers.createPathVarBuffers(pathVarNames)
        val stepVarBuffers = DataSetBuffers.createStepVarBuffers(stepVarNames)        
        val head = expr.transform(wordNet, bindings, context, data, pos, force)

        for (i <- 0 until head.pathCount) {
          val tuple = head.paths(i)
          val prefix = tuple.slice(0, tuple.size - 1)
          
          pathBuffer.append(tuple)
          pathVarNames.foreach(x => pathVarBuffers(x).append(head.pathVars(x)(i)))
          stepVarNames.foreach(x => stepVarBuffers(x).append(head.stepVars(x)(i)))          

          for (cnode <- closure(wordNet, bindings, context, expr, List(tuple.last), Set(tuple.last))) {
            pathBuffer.append(prefix ++ cnode)
            pathVarNames.foreach(x => pathVarBuffers(x).append(head.pathVars(x)(i)))
            stepVarNames.foreach(x => stepVarBuffers(x).append(head.stepVars(x)(i)))        
          }
        }
        
        DataSet.fromBuffers(pathBuffer, pathVarBuffers, stepVarBuffers)
      case _ =>
        throw new IllegalArgumentException("Unsupported quantifier value " + quantifier)
    }
  }
  
  private def closure(wordNet: WordNet, bindings: Bindings, context: Context, expr: RelationalExpr,
    source: List[Any], forbidden: Set[Any]): List[List[Any]] = {
    val transformed = expr.transform(wordNet, bindings, context, DataSet.fromTuple(source), 1, true)
    val filtered = transformed.paths.filter { x => !forbidden.contains(x.last) }

    if (filtered.isEmpty) {
      filtered
    } else {
      val result = new ListBuffer[List[Any]]
      val newForbidden: Set[Any] = forbidden.++[Any, Set[Any]](filtered.map { x => x.last }) // TODO ugly

      result.appendAll(filtered)

      filtered.foreach { x =>
        result.appendAll(closure(wordNet, bindings, context, expr, x, newForbidden))
      }

      result.toList
    }
  }  
}

case class UnionRelationalExpr(lexpr: RelationalExpr, rexpr: RelationalExpr) extends RelationalExpr {
  def transform(wordNet: WordNet, bindings: Bindings, context: Context, data: DataSet, pos: Int, force: Boolean) = {
    val lresult = lexpr.transform(wordNet, bindings, context, data, pos, force)
    val rresult = rexpr.transform(wordNet, bindings, context, data, pos, force)

    DataSet(lresult.paths union rresult.paths,
      lresult.pathVars.map(x => (x._1, x._2 ++ rresult.pathVars(x._1))),
      lresult.stepVars.map(x => (x._1, x._2 ++ rresult.stepVars(x._1)))
    )
  }
}

/*
 * Conditional Expressions
 */
sealed abstract class ConditionalExpr extends Expr {
  def satisfied(functions: FunctionSet, wordNet: WordNet, bindings: Bindings, context: Context): Boolean
}

case class OrExpr(exprs: List[ConditionalExpr]) extends ConditionalExpr {
  def satisfied(functions: FunctionSet, wordNet: WordNet, bindings: Bindings, context: Context) = exprs.exists { x => x.satisfied(functions, wordNet, bindings, context) }
}

case class AndExpr(exprs: List[ConditionalExpr]) extends ConditionalExpr {
  def satisfied(functions: FunctionSet, wordNet: WordNet, bindings: Bindings, context: Context) = exprs.forall { x => x.satisfied(functions, wordNet, bindings, context) }
}

case class NotExpr(expr: ConditionalExpr) extends ConditionalExpr {
  def satisfied(functions: FunctionSet, wordNet: WordNet, bindings: Bindings, context: Context) = !expr.satisfied(functions, wordNet, bindings, context)
}

case class ComparisonExpr(op: String, lexpr: EvaluableExpr, rexpr: EvaluableExpr) extends ConditionalExpr {
  def satisfied(functions: FunctionSet, wordNet: WordNet, bindings: Bindings, context: Context) = {
    val lresult = lexpr.evaluate(functions, wordNet, bindings, context).paths.map(x => x.last)
    val rresult = rexpr.evaluate(functions, wordNet, bindings, context).paths.map(x => x.last)

    op match {
      case "=" =>
        lresult.forall(rresult.contains) && rresult.forall(lresult.contains)
      case "!=" =>
        !(lresult.forall(rresult.contains) && rresult.forall(lresult.contains))
      case "in" =>
        lresult.forall(rresult.contains)
      case "pin" =>
        lresult.forall(rresult.contains) && lresult.size < rresult.size
      case "=~" =>
        if (rresult.size == 1 ) {
          // element context
          if (DataType(rresult.head) == StringType) {
            val regex = rresult.head.asInstanceOf[String].r

            lresult.forall {
              case elem: String =>
                regex findFirstIn (elem) match {
                  case Some(_) =>
                    true
                  case None =>
                    false
                }
            }
          } else {
            throw new WQueryEvaluationException("The right side of '" + op +
              "' should return exactly one character string value")
          }
        } else if (rresult.isEmpty) {
          throw new WQueryEvaluationException("The right side of '" + op + "' returns no values")
        } else { // rresult.pathCount > 0
          throw new WQueryEvaluationException("The right side of '" + op + "' returns more than one values")
        }
      case _ =>
        if (lresult.size == 1 && rresult.size == 1) {
          // element context
          op match {
            case "<=" =>
              WQueryFunctions.compare(lresult, rresult) <= 0
            case "<" =>
              WQueryFunctions.compare(lresult, rresult) < 0
            case ">=" =>
              WQueryFunctions.compare(lresult, rresult) >= 0
            case ">" =>
              WQueryFunctions.compare(lresult, rresult) > 0
            case _ =>
              throw new IllegalArgumentException("Unknown comparison operator '" + op + "'")
          }
        } else {
          if (lresult.isEmpty)
            throw new WQueryEvaluationException("The left side of '" + op + "' returns no values")
          if (lresult.size > 1)
            throw new WQueryEvaluationException("The left side of '" + op + "' returns more than one value")
          if (rresult.isEmpty)
            throw new WQueryEvaluationException("The right side of '" + op + "' returns no values")
          if (rresult.size > 1)
            throw new WQueryEvaluationException("The right side of '" + op + "' returns more than one values")

          // the following shall not happen
          throw new WQueryEvaluationException("Both sides of '" + op + "' should return exactly one value")
        }
    }
  }
}

/*
 * Generators
 */
case class SynsetAllReq() extends FunctionsFreeExpr {
  def evaluate(wordNet: WordNet) = DataSet.fromList(wordNet.synsets.toList)
}

case class SynsetByExprReq(expr: EvaluableExpr) extends EvaluableExpr {
  def evaluate(functions: FunctionSet, wordNet: WordNet, bindings: Bindings, context: Context) = {
    val eresult = expr.evaluate(functions, wordNet, bindings, context)

    if (eresult.pathCount == 1 && eresult.minPathSize == 1 && eresult.maxPathSize == 1) {
      if (eresult.getType(0) == SenseType) {
        DataSet(eresult.paths.map { case List(sense: Sense) => List(wordNet.getSynsetBySense(sense)) })
      } else if (eresult.getType(0) == StringType) {          
        DataSet(eresult.paths.flatMap { case List(wordForm: String) => wordNet.getSynsetsByWordForm(wordForm) }.map(x => List(x)))  
      } else {
        throw new WQueryEvaluationException("{...} requires an expression that generates either senses or word forms")  
      }           
    } else if (eresult.pathCount == 0) {
        DataSet.empty
    } else {
      throw new WQueryEvaluationException("{...} requires an expression that generates single element paths")        
    }
  }
}

case class SenseAllReq() extends FunctionsFreeExpr {
  def evaluate(wordNet: WordNet) = DataSet.fromList(wordNet.senses.toList)
}

case class SenseByWordFormAndSenseNumberAndPosReq(word: String, num: Int, pos: String) extends FunctionsFreeExpr {
  def evaluate(wordNet: WordNet) = DataSet.fromOptionalValue(wordNet.getSenseByWordFormAndSenseNumberAndPos(word, num, pos))
}

case class SenseByWordFormAndSenseNumberReq(word: String, num: Int) extends FunctionsFreeExpr {
  def evaluate(wordNet: WordNet) = DataSet.fromList(wordNet.getSensesByWordFormAndSenseNumber(word, num))
}

case class ContextByRelationalExprReq(expr: RelationalExpr) extends EvaluableExpr {
  def evaluate(functions: FunctionSet, wordNet: WordNet, bindings: Bindings, context: Context) = {
    expr.transform(wordNet, bindings, context, DataSet(List(context.values)), 0, false)
  }
}

case class WordFormByRegexReq(v: String) extends FunctionsFreeExpr {
  def evaluate(wordNet: WordNet) = {
    val regex = v.r
    val result = wordNet.words.filter { x =>
      regex findFirstIn (x) match {
        case Some(s) =>
          true
        case None =>
          false
      }
    }

    DataSet.fromList(result.toList)
  }
}

case class ContextByReferenceReq(ref: Int) extends EvaluableExpr {
  def evaluate(functions: FunctionSet, wordNet: WordNet, bindings: Bindings, context: Context) = {
    if (context.size - ref >= 0) {
      val value = context.values(context.size - ref)
      DataSet.fromValue(if (value.isInstanceOf[List[_]]) value.asInstanceOf[List[_]].last else value)
    } else {
      throw new WQueryEvaluationException("Backward reference '" + List.fill(ref)("#").mkString +
        "' too far, the longest possible backward reference in this context is '" +
        List.fill(context.size)("#").mkString + "'")
    }
  }
}

case class ContextByVariableReq(variable: VariableLit) extends ContextFreeExpr {
  def evaluate(functions: FunctionSet, wordNet: WordNet, bindings: Bindings) = {
    bindings.lookup(variable.value) match {// TODO distinguish between path and step variables
      case Some(value) =>
        DataSet.fromValue(value)
      case None =>
        throw new WQueryEvaluationException("A reference to unknown variable '" + variable.value + "' found")
    }
  }
}

case class BooleanByFilterReq(cond: ConditionalExpr) extends ContextFreeExpr {
  def evaluate(functions: FunctionSet, wordNet: WordNet, bindings: Bindings) = DataSet.fromValue(cond.satisfied(functions, wordNet, bindings, Context.empty))
}

/*
 * Variables
 */
case class GeneratorExpr(expr: EvaluableExpr, decls: List[VariableLit]) extends EvaluableExpr with VariableBindings {
  def evaluate(functions: FunctionSet, wordNet: WordNet, bindings: Bindings, context: Context) = {
    bind(expr.evaluate(functions, wordNet, bindings, context), decls)
  }
}

sealed abstract class VariableLit(val value: String) extends Expr

case class StepVariableLit(override val value: String) extends VariableLit(value)
case class PathVariableLit(override val value: String) extends VariableLit(value)

/*
 * Literals
 */
case class DoubleQuotedLit(value: String) extends SelfEvaluableExpr {
  def evaluate = DataSet.fromValue(value)
}

case class StringLit(value: String) extends SelfEvaluableExpr {
  def evaluate = DataSet.fromValue(value)
}

case class IntegerLit(value: Int) extends SelfEvaluableExpr {
  def evaluate = DataSet.fromValue(value)
}

case class SequenceLit(left: Int, right: Int) extends SelfEvaluableExpr {
  def evaluate = DataSet.fromList((left to right).toList)
}

case class FloatLit(value: Double) extends SelfEvaluableExpr {
  def evaluate = DataSet.fromValue(value)
}

case class BooleanLit(value: Boolean) extends SelfEvaluableExpr {
  def evaluate = DataSet.fromValue(value)
}

case class QuantifierLit(left: Int, right: Option[Int]) extends Expr

sealed abstract class IdentifierLit(val value: String) extends SelfEvaluableExpr {
  def evaluate = DataSet.fromValue(value)
}

case class NotQuotedIdentifierLit(override val value: String) extends IdentifierLit(value)
case class QuotedIdentifierLit(override val value: String) extends IdentifierLit(value)